openapi: 3.0.3
info:
  title: DigitalCity Public API
  version: "1.0.0"
  description: |
    Public, read‑only API for DigitalCity.
servers:
  - url: https://example.com
paths:
  /api/v2/posts:
    get:
      summary: List posts
      parameters:
        - in: query
          name: q
          schema: { type: string }
          description: Optional text query
        - in: query
          name: page
          schema: { type: integer, minimum: 1 }
      responses:
        "200":
          description: OK
  /api/v2/pages:
    get:
      summary: List pages
      responses:
        "200": { description: OK }
  /api/search:
    get:
      summary: Search posts & pages
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
components:
  securitySchemes: {}

