name: CI
on: [push, pull_request]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql, pgsql, curl
          coverage: none

      - name: Install deps (with dev)
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare app key
        run: cp .env.example .env && php artisan key:generate --no-interaction

      - name: Run tests
        run: php artisan test -q --no-interaction
