name: CI
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
on: [push, pull_request, workflow_dispatch]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      APP_ENV: testing
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: sqlite3, pdo_sqlite, curl
          coverage: none

      - name: Cache Composer downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare .env (sqlite) & APP_KEY
        run: |
          cp -n .env.example .env || true
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env || echo "DB_CONNECTION=sqlite" >> .env
          sed -i 's#^DB_DATABASE=.*#DB_DATABASE=database/testing.sqlite#' .env || echo "DB_DATABASE=database/testing.sqlite" >> .env
          mkdir -p database && touch database/testing.sqlite
          php artisan key:generate --no-interaction --force

      - name: Migrate
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test -q
