name: Deploy (manual)
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server & deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /var/www/imdc
            git fetch --all --tags
            git reset --hard origin/main
            composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader --no-dev
            php artisan key:generate --force || true
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
